import { randomUUID } from 'node:crypto';
import { copyFile, mkdir, rename, rm, stat, unlink } from 'node:fs/promises';
import path from 'node:path';
import type { Response } from 'express';
import { env } from '../../config/env.js';
import { AppError } from '../../lib/errors.js';

// Where files live is hidden behind this interface. Today: local disk.
// Moving to object storage later (e.g. S3/R2) means writing one new class,
// without touching the modules that upload or serve files.
export interface StorageService {
  /** Moves a validated temp file into storage under `key`. */
  save(tempPath: string, key: string): Promise<void>;
  /** Streams the file to the client (with HTTP Range support for video seeking). */
  send(key: string, res: Response, headers: Record<string, string>): Promise<void>;
  exists(key: string): Promise<boolean>;
  delete(key: string): Promise<void>;
}

export class LocalDiskStorage implements StorageService {
  private readonly root: string;

  constructor(root: string) {
    this.root = path.resolve(root);
  }

  // Keys are generated by us, but we still make sure a key can never escape the
  // upload folder (e.g. "../../.env").
  private pathFor(key: string) {
    const full = path.resolve(this.root, key);
    if (!full.startsWith(this.root + path.sep)) throw AppError.badRequest('Invalid file key');
    return full;
  }

  async save(tempPath: string, key: string) {
    const target = this.pathFor(key);
    await mkdir(path.dirname(target), { recursive: true });
    try {
      await rename(tempPath, target);
    } catch {
      // rename fails across disks (temp folder on another drive): copy instead
      await copyFile(tempPath, target);
      await unlink(tempPath).catch(() => {});
    }
  }

  async send(key: string, res: Response, headers: Record<string, string>) {
    const full = this.pathFor(key);
    if (!(await this.exists(key))) throw AppError.notFound('File not found');
    await new Promise<void>((resolve, reject) => {
      // sendFile handles Range requests, ETags and streaming for us.
      res.sendFile(full, { headers, dotfiles: 'deny' }, (err) => (err ? reject(err) : resolve()));
    });
  }

  async exists(key: string) {
    try {
      return (await stat(this.pathFor(key))).isFile();
    } catch {
      return false;
    }
  }

  async delete(key: string) {
    await rm(this.pathFor(key), { force: true });
  }
}

export const storage: StorageService = new LocalDiskStorage(env.UPLOAD_DIR);

// e.g. "certificates/2026/5f0c...e1.pdf" - never the user's own file name.
export function newFileKey(category: 'certificates' | 'qualifications' | 'evidence' | 'library', extension: string) {
  return `${category}/${new Date().getFullYear()}/${randomUUID()}${extension}`;
}
